authorization: suggest protobuf for events
plgd-dev/hub pull request #390
Opened 2021-08-09 16:04 UTC by jkralik

2021-08-09 20:47 UTC, ondrejtomcik commented on authorization/pb/events.proto
> +message RegisteredDevices {
The event described what has happened.
`DevicesRegistered`and `DevicesUnregistered`.

2021-08-09 20:50 UTC, ondrejtomcik commented on authorization/pb/events.proto
> +    int64 timestamp = 3; // unix timestamp in nanoseconds of creation event.
I miss our AuditContext, which is helpful if somebody is building an audit log and you want to track who shared the device with this new owner.

2021-08-09 20:54 UTC, ondrejtomcik commented on authorization/pb/events.proto
> +message Event {
For resource-related events, we don't have such an envelope. Developers working with NATS won't like two different approaches. I would organize event types per subjects, as we do with RA.

2021-08-10 07:31 UTC, jkralik commented on authorization/pb/events.proto
> +message Event {
No. As a developer sometimes I want to be subscribed at  `owners.{owner}.>` to get all events. If I subscribe lower then I need to get the subject that provided the event. And I don't want to push the dependence to nats to the protocol.

2021-08-10 07:38 UTC, ondrejtomcik commented on authorization/pb/events.proto
> +message Event {
It's okay to organize it per as you defined -> `owners.{owner}.>`. My point is that `DevicesRegistered` shall be pushed to `owners.{owner}.deviceregistered` and `DevicesUnregistered` to `owners.{owner}.deviceunregistered`. This follows existing concepts you already introduced in RA.

2021-08-11 09:09 UTC, Danielius1922 approved these changes

2021-08-11 09:10 UTC, Danielius1922 requested changes
Static analysis failed

2021-08-11 09:29 UTC, ondrejtomcik approved these changes

2021-08-11 10:20 UTC, Danielius1922 approved these changes

2021-08-11 11:10 UTC, merged